openapi: 3.0.0
info:
  title: common technical data types
  description: common types in beta status
  version: v1beta
servers: []
tags:
  - name: Monitoring
paths:
  /health:
    get:
      tags:
        - Monitoring
      summary: Check health of this REST API
      description: Get the health of this API. Inspired on https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready
      operationId: health
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
          description: The service is up
        '503':
          description: The service is down or outOfService
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
              examples:
                response:
                  value: {
                    'status': 'down',
                    'details': {
                      'datastore': {
                        'status': 'outOfService'
                      }
                    }
                  }
components:
  schemas:
    HealthStatus:
      description: Response message for the API health 
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/HealthLevel'
        details:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ComponentStatus'
    ComponentStatus:
      description: Status of an API component 
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/HealthLevel'
    HealthLevel:
      description: Status of the health check. Inspired on https://github.com/spring-projects/spring-boot/blob/v2.0.3.RELEASE/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/Status.java
      type: string
      enum:
        - up
        - degraded
        - down
        - unknown
        - outOfService